---
- name: download mesos-dns
  get_url: url='{{mesos_dns_url}}' dest='/tmp/{{mesos_dns_app}}'

#- name: un-gz
#  shell: gunzip -c '/tmp/{{mesos_dns_app_gz}}' > '{{installed_mesos_dns_app}}'
#  args:
#    creates: '{{installed_mesos_dns_app}}'

- name: move to bin
  shell: "mv /tmp/{{mesos_dns_app}} {{installed_mesos_dns_app}}"
  args:
    creates: '{{installed_mesos_dns_app}}'

- name: chmod to executable
  file: path={{installed_mesos_dns_app}} mode=0755
    
- name: link
  file: >
    src='{{installed_mesos_dns_app}}'
    dest='{{mesos_dns_target_dir}}/mesos-dns'
    state=link
    
- name: Check if systemd exists
  stat: path=/lib/systemd/system/
  register: systemd_check

- name: Mesos-DNS systemd script
  template: src=mesos-dns.service.j2 dest=/lib/systemd/system/mesos-dns.service
  when: systemd_check.stat.exists == true
  notify:
    - Reload daemon
    - Restart mesos-dns

- name: Enable/Disable mesos-dns service
  service: name=mesos-dns enabled="yes"
  when: systemd_check.stat.exists == true
    
