- name: Reload daemon
  command: systemctl daemon-reload
  when: ansible_service_mgr == 'systemd'

- name: Restart mesos-dns
  service: name=mesos-dns state=restarted
#  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"
